# Latent Semantic Indexing (LSI)

In [1]:
import sys 
import heapq 
import math
from collections import defaultdic
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

In [3]:
def extract(filename):
    unformatted_words = []
    with open(filename,'r') as file:      
        for line in file:     
            for word in line.split():   
                unformatted_words.append(word)
    punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~1234567890'''
    dict_list=[]
    for word in unformatted_words:
        no_punct = ""
        for character in word:
            if character not in punctuations:
                no_punct = no_punct + character
        if no_punct != "":
            dict_list.append(no_punct.lower())
    key = []
    for word in dict_list:
        if word not in key:
            key.append(word)
    freq = []
    for i in range(len(key)):
        freq.append(dict_list.count(key[i]))
    dictionary=[]
    for i in range(len(key)):
        dictionary.append((key[i],freq[i]))
    dictionary.sort(key = lambda x: x[0])
    return dictionary

In [4]:
def unpack(words):
    punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~1234567890'''
    dict_list=[]
    for word in words:
        no_punct = ""
        for char in word:
            if char not in punctuations:
                no_punct = no_punct + char
        if no_punct != "":
            dict_list.append(no_punct.lower())
    key = []
    for word in dict_list:
        if word not in key:
            key.append(word)
    freq = []
    for i in range(len(key)):
        freq.append(dict_list.count(key[i]))
    return key,freq
def get_vector(query_words,query_term_freq,final_words):
    query_vector=[]
    for word in final_words:
        if word not in query_words:
            query_vector.append(0)
        else:
            for i in range(len(query_words)):
                if word == query_words[i]:
                    query_vector.append(query_term_freq[i])
    query_vector=np.array(query_vector)
    return query_vector

In [5]:
def get_term_document_matrix(doc_list):
    n = len(doc_list)
    final_words=[]
    for i in range(n):
        for word,freq in doc_list[i]:
            if word not in final_words:
                final_words.append(word)
    final_words.sort()
    matrix=[]
    for word in final_words:
        temp=[]
        for i in range(n):
            present = False
            for doc_word,term_freq in doc_list[i]:
                if doc_word==word:
                    present = True
                    temp.append(term_freq)
            if present == False:
                temp.append(0)
        matrix.append(temp)
    return final_words,matrix

In [6]:
dict1 = extract_from_file("d1.txt")
dict2 = extract_from_file("d2.txt")
dict3 = extract_from_file("d3.txt")
doc_list=[dict1,dict2,dict3]
final_words,matrix = get_term_document_matrix(doc_list)
matrix = np.array(matrix)
print(final_words)
print(matrix)

['a', 'according', 'act', 'action', 'affects', 'after', 'against', 'also', 'and', 'are', 'as', 'be', 'been', 'being', 'but', 'by', 'can', 'cannot', 'causing', 'characteristic', 'classic', 'classical', 'collapse', 'copenhagen', 'creates', 'darwinian', 'darwinism', 'definite', 'determine', 'distribution', 'do', 'doubleslit', 'due', 'emergence', 'environment', 'eraser', 'establishes', 'experiment', 'explain', 'favor', 'feature', 'fringe', 'fringes', 'from', 'function', 'generally', 'given', 'has', 'have', 'immediately', 'in', 'induced', 'interacting', 'interfere', 'interference', 'interpretation', 'is', 'it', 'itself', 'known', 'later', 'level', 'many', 'marked', 'material', 'meant', 'measured', 'measurement', 'measurements', 'mechanics', 'microscopic', 'natural', 'not', 'objects', 'of', 'on', 'one', 'only', 'passed', 'patterns', 'photon', 'photons', 'pointer', 'possible', 'predict', 'prior', 'probabilities', 'probability', 'process', 'produce', 'properties', 'quantum', 'reduce', 'results

In [7]:
U, Sigma, V_t = np.linalg.svd(matrix, full_matrices=False)

In [8]:
print("U:",U)
print("\nSigma:",Sigma)
print("\nV:",V_t)

U: [[-0.33302576  0.00670728 -0.13927323]
 [-0.01750194  0.06060638  0.08796958]
 [-0.01750194  0.06060638  0.08796958]
 [-0.0420606  -0.04128692  0.0051178 ]
 [-0.01750194  0.06060638  0.08796958]
 [-0.01750194  0.06060638  0.08796958]
 [-0.01521942  0.04440534 -0.11530639]
 [-0.0420606  -0.04128692  0.0051178 ]
 [-0.14368376 -0.06325438  0.10332297]
 [-0.01521942  0.04440534 -0.11530639]
 [-0.03272136  0.10501172 -0.02733681]
 [-0.08412121 -0.08257384  0.01023559]
 [-0.12618181 -0.12386076  0.01535339]
 [-0.01750194  0.06060638  0.08796958]
 [-0.0420606  -0.04128692  0.0051178 ]
 [-0.01521942  0.04440534 -0.11530639]
 [-0.05956255  0.01931946  0.09308738]
 [-0.08412121 -0.08257384  0.01023559]
 [-0.01750194  0.06060638  0.08796958]
 [-0.08412121 -0.08257384  0.01023559]
 [-0.0420606  -0.04128692  0.0051178 ]
 [-0.01521942  0.04440534 -0.11530639]
 [-0.01750194  0.06060638  0.08796958]
 [-0.01750194  0.06060638  0.08796958]
 [-0.0420606  -0.04128692  0.0051178 ]
 [-0.01521942  0.04440

In [9]:
U_new = np.delete(U, -1, axis=1)
V_t_new = np.delete(V_t, -1,axis=0)
Sigma_new = np.delete(Sigma,-1)

In [10]:
print("U:",U_new)
print("\nSigma:",Sigma_new)
print("\nV:",V_t_new)

U: [[-0.33302576  0.00670728]
 [-0.01750194  0.06060638]
 [-0.01750194  0.06060638]
 [-0.0420606  -0.04128692]
 [-0.01750194  0.06060638]
 [-0.01750194  0.06060638]
 [-0.01521942  0.04440534]
 [-0.0420606  -0.04128692]
 [-0.14368376 -0.06325438]
 [-0.01521942  0.04440534]
 [-0.03272136  0.10501172]
 [-0.08412121 -0.08257384]
 [-0.12618181 -0.12386076]
 [-0.01750194  0.06060638]
 [-0.0420606  -0.04128692]
 [-0.01521942  0.04440534]
 [-0.05956255  0.01931946]
 [-0.08412121 -0.08257384]
 [-0.01750194  0.06060638]
 [-0.08412121 -0.08257384]
 [-0.0420606  -0.04128692]
 [-0.01521942  0.04440534]
 [-0.01750194  0.06060638]
 [-0.01750194  0.06060638]
 [-0.0420606  -0.04128692]
 [-0.01521942  0.04440534]
 [-0.01521942  0.04440534]
 [-0.01750194  0.06060638]
 [-0.0420606  -0.04128692]
 [-0.01750194  0.06060638]
 [-0.01750194  0.06060638]
 [-0.0420606  -0.04128692]
 [-0.01521942  0.04440534]
 [-0.01521942  0.04440534]
 [-0.01521942  0.04440534]
 [-0.0420606  -0.04128692]
 [-0.0420606  -0.04128692

In [11]:
query = input("Enter query :").split(" ")

Enter query :Copenhagen interpretation and quantum darwinism.


In [12]:
#get the query terms and their frequencies
query_words,query_term_freq = unpack_document(query)
#convert query into vector
query_vector = get_vector(query_words,query_term_freq,final_words)
print(query_vector)

[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [13]:
#convert query into new reduced 2-dimensional query
new_query = np.matmul(query_vector.transpose(),U_new)
new_query = np.matmul(new_query,np.linalg.inv(np.diag(np.diag(V_t_new))))
print(new_query)

[ 0.99206361 -0.62148698]


In [14]:
#unpack terms from documents of corpus
words = []
for dict_ in doc_list:
    words.append([a_tuple[0] for a_tuple in dict_])

#calculate terms and term_frequencies for documents in a corpus
doc_words,doc_tf=[],[]
for word_ in words:
    temp1,temp2=unpack_document(word_)
    doc_words.append(temp1)
    doc_tf.append(temp2)

#convert documents into vectors
doc_vectors=[]
for i in range(len(doc_words)):
    doc_vectors.append(get_vector(doc_words[i],doc_tf[i],final_words))

#reducing the document vector dimension
reduced_doc_vectors=[]
for doc_vector in doc_vectors:
    reduced_doc_vector = np.matmul(doc_vector.transpose(),U_new)
    reduced_doc_vector = np.matmul(reduced_doc_vector,np.linalg.inv(np.diag(np.diag(V_t_new))))
    reduced_doc_vectors.append(reduced_doc_vector)

In [15]:
print(reduced_doc_vectors)

[array([ 7.4848079 , -5.28866539]), array([18.47348676,  5.62827557]), array([ 8.85015934, -8.1399438 ])]


In [16]:
#calculate cosine score
scores = []
for i in range(len(reduced_doc_vectors)):
    doc_score = cosine_similarity([new_query], [reduced_doc_vectors[i]])
    scores.append(doc_score[0][0])

In [17]:
ranked_documents=[]
for i in range(len(doc_list)):
    ranked_documents.append(("document-"+str(i+1),scores[i]))
ranked_documents.sort(key = lambda x: x[1],reverse=True)

In [18]:
print(ranked_documents)

[('document-1', 0.998461090077326), ('document-3', 0.983124624951171), ('document-2', 0.6559307714729127)]
